version: '3.8'

services:
  pgvector:
    image: phidata/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


volumes:
  pgvolume:
